<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Tags\Tag;

class TagsSeeder extends Seeder
{
    public $list = [
        'API Resources',
        'Artisan Console',
        'Asset Bundling',
        'Authentication',
        'Authorization',
        'Blade Templates',
        'Breeze',
        'Broadcasting',
        'Browser Tests',
        'Cache',
        'Cashier',
        'Collections',
        'Collections',
        'Console Tests',
        'Context',
        'Contracts',
        'Controllers',
        'CSRF Protection',
        'Database Tests',
        'Deployment',
        'Dusk',
        'Echo',
        'Email Verification',
        'Encryption',
        'Envoy',
        'Envoyer',
        'Error Handling',
        'Events',
        'Facades',
        'Factories',
        'File Storage',
        'Folio',
        'Forge',
        'Fortify',
        'Hashing',
        'Helpers',
        'Herd',
        'Homestead',
        'Horizon',
        'HTTP Client',
        'HTTP Tests',
        'Inertia',
        'Jetstream',
        'Livewire',
        'Localization',
        'Logging',
        'Mail',
        'Middleware',
        'Migrations',
        'Mix',
        'Mocking',
        'Mutators / Casts',
        'Notifications',
        'Nova',
        'Octane',
        'Package Development',
        'Pagination',
        'Passport',
        'Password Reset',
        'Pennant',
        'Pint',
        'Precognition',
        'Processes',
        'Prompts',
        'Pulse',
        'Query Builder',
        'Queues',
        'Rate Limiting',
        'Redis',
        'Relationships',
        'Request Lifecycle',
        'Requests',
        'Responses',
        'Reverb',
        'Routing',
        'Sail',
        'Sanctum',
        'Scout',
        'Seeding',
        'Serialization',
        'Service Container',
        'Service Providers',
        'Session',
        'Socialite',
        'Spark',
        'Strings',
        'Task Scheduling',
        'Telescope',
        'URL Generation',
        'Valet',
        'Validation',
        'Vapor',
        'Views',
    ];

    public function run(): void
    {
        Tag::findOrCreate($this->list);
    }
}
